修改一些匹配规则；添加函数注释；删去coc模块
dailongao/Chiyuki-Bot pull request #1
Opened 2021-03-14 09:19 UTC by KanuaK

2021-03-14 09:40 UTC, dailongao requested changes

2021-03-14 09:40 UTC, dailongao commented on src/plugins/image.py
> +    regex = '/低情商(.+)高情商(.+)'
这个我之前也这么改的，后来发现是配置项问题
https://v2.nonebot.dev/guide/basic-configuration.html
COMMAND_START=["/", ""]  # 配置命令起始字符
但我实在没有懂为什么用/就匹配不上了，我觉得应该是源代码的regex还是有问题，但不是这么改

2021-03-14 09:40 UTC, dailongao commented on src/plugins/maimaidx.py
> +spec_rand = on_regex(r"^/随个(?:dx|sd|标准)?[绿黄红紫白]?[0-9]+\+?")
^

2021-03-14 09:40 UTC, dailongao commented on src/plugins/maimaidx.py
> +search_music = on_regex(r"^/查歌.+")
^

2021-03-14 09:40 UTC, dailongao commented on src/plugins/maimaidx.py
> +    regex = "/查歌(.+)"
^

2021-03-14 09:40 UTC, dailongao commented on src/plugins/maimaidx.py
> +query_chart = on_regex(r"^/([绿黄红紫白]?)id([0-9]+)")
^

2021-03-14 09:40 UTC, dailongao commented on src/plugins/maimaidx.py
> +find_song = on_regex(r"/.+是什么歌")
^

2021-03-14 09:40 UTC, dailongao commented on src/plugins/maimaidx.py
> +    regex = "/(.+)是什么歌"
^

2021-03-14 09:40 UTC, dailongao commented on src/plugins/public.py
> +random_person = on_regex("/随个([男女]?)人")
^

2021-03-14 09:40 UTC, dailongao commented on src/plugins/public.py
> +snmb = on_regex("/随个.+", priority=50)
^

2021-03-14 09:51 UTC, KanuaK commented on src/plugins/image.py
> +    regex = '/低情商(.+)高情商(.+)'
那个应该是command起始字符，他一部分用了on_command一部分用了on_regex，regex是直接匹配不用加起始字符的，他帮助信息里面写的.help应该就是改配置文件弄的

2021-03-31 07:48 UTC, dailongao approved these changes

2021-03-31 07:48 UTC, merged